### ISSUE TITLE
something strange with tinyMCE adaptor

### ISSUE THREAD

**Issue by originalsurfmex** [django-inplaceedit/django-inplaceedit-extra-fields#6]
virtualenvironment:
````
    python 3.3
    django 1.6
    django-inplaceedit-extra-fields==0.5.0
    django-inplaceedit==1.3.0
    django-grappelli==2.5.2
    django-filebrowser==3.5.4
````

When I edit a plain text item using the tinyMCE adaptor things work good, but after that the text is uneditable via inplaceedit.

For example if I start with:

`some unformatted text`

then I can double click and edit it, but if it saves with any kind of markup for example:

`<p>some unformatted <em>text</em></p>`

then I can no longer double click and edit it.  Even more strange, if I go to my template and add change `{% inplace_edit "item.about_story" adaptor="tiny" %}`  to `{% inplace_edit "item.about_story" | safe adaptor="tiny" %}`  - then my page renders unformatted text with markup but it is also then stuck in the tinyMCE edit mode.

My project is located here for reference:
https://github.com/originalsurfmex/addition_interiors_project

Model name: `class About`
View name: `class AboutDetail`
Template name: `about_list.html`

My settings file:
https://github.com/originalsurfmex/addition_interiors_project/blob/master/addition_interiors_project/settings.py
My models file:
https://github.com/originalsurfmex/addition_interiors_project/blob/master/frontpage/models.py
My views file:
https://github.com/originalsurfmex/addition_interiors_project/blob/master/frontpage/views.py
My template:
https://github.com/originalsurfmex/addition_interiors_project/blob/master/frontpage/templates/frontpage/about_list.html

**Comment by goinnn** [comment]
I'm sorry for delay. I suppose that you fixed it.
